spring:
  security:
    user:
      password: 8708fb7d-6db9-4958-ac1f-b87c834d5b6d

  devtools:
    restart:
      enabled: true
      poll-interval: 2s
      quiet-period: 1s
      trigger-file: .reloadtrigger
    livereload:
      enabled: true
      port: 35729
  web:
    resources:
      cache:
        period: 0
      chain:
        cache: false
  datasource:
    url: jdbc:postgresql://localhost:5432/postgresdb
    username: developer
    password: devpass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        '[format_sql]': true
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    root: INFO
    '[com.hubpedro]': DEBUG
    '[org.springframework.web]': DEBUG
    '[org.hibernate.SQL]': DEBUG
    '[org.hibernate.type.descriptor.sql.BasicBinder]': TRACE
    '[org.springframework.boot.devtools]': DEBUG
    '[org.springframework.security]': DEBUG
  pattern:
    console: "%clr(%d{HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"

# Actuator para monitoramento
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,loggers
  endpoint:
    health:
      show-details: always
    loggers:
      access: read_only

# Configuração do servidor
server:
  port: 8080
  error:
    include-stacktrace: always
    include-message: always
    include-exception: true
    include-binding-errors: always
    include-path: always
  servlet:
    context-path: /
springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
  default-consumes-media-type: application/json
  default-produces-media-type: application/json


jwt:
  secret: ${JWT_SECRET:100aa1ca3f3948f0b15f80da132f640d}
  expiration: ${JWT_EXPIRATION:3600000}